### ISSUE TITLE
Mortal Kombat II: Game does not autodetect Six Button Controller

### ISSUE THREAD

**Issue by air-10** [OpenEmu/GenesisPlus-Core#2]
When running Mortal Combats (any versions) on Sega Mega Drive you can not use Y and B joystick buttons on your macbook pro keyboard. They either dont work or work as a C button. 

Mac OS 10.14.4
OpenEmu 2.0.8

Troubleshooting page doesnt help, Chrome browser is closed, no apps running.

**Comment by clobber** [comment]
>any versions

Cannot replicate this with Mortal Kombat, Ultimate Mortal Kombat 3 or the ROM hack known as "Ultimate Mortal Kombat Trilogy". There *does* appear to be an issue with Mortal Kombat II where the game thinks the "Sega Activator" is plugged in instead of the "Six Button Control Pad". This can temporarily be resolved by going into the game options and changing the port settings in "Extra Controls". I'll investigate.

**Comment by air-10** [comment]
I am sorry, this is only an MK1 and MK2 issue only. The MK3, as you said, works just fine!
Thank you for that temporary solution to switch sega activator off in options for mk2! Sadly there is no such setting in mk1 menu.

Here are the ROMs I have used:
mk1:   http://dl2.emu-land.net/roms/gen/Mortal%20Kombat.7z
mk2:   http://dl2.emu-land.net/roms/gen/Mortal%20Kombat%20II.7z

**Comment by clobber** [comment]
Again, the problem cannot be replicated on the official release of Mortal Kombat.

MD5 checksum: a1dd8a3e4b8c98dee49d5e90d6b87903
Possible filenames: Mortal Kombat (W) (REV00) [!].gen or Mortal Kombat (World).md
https://datomatic.no-intro.org/?page=show_record&s=32&n=0861

Please do not link to ROM downloads here.

**Comment by air-10** [comment]
Wow, I have just tried it and you're right, the version with this exact checksum you posted works fine!
I must just go for it, ignoring all other releases\iterations. For mk1 the problem is kinda solved! 
But mk2 still thinks that sega activator is plugged in. Your solution with going into options in mk2 and switching for gamepad is a good working one too! Thank you for helping!!!

**Comment by clobber** [comment]
According to the manual, on real hardware you would always have to select the use of the Six Button Control Pad from the options despite having it plugged in.

https://segaretro.org/index.php?title=File:Mortal_Kombat_II_MD_US_Manual.pdf&page=3

Closing; non-issue here.
